In [ ]:
# mengimpor data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



In [28]:
dataset = pd.read_csv('dataset.csv', sep=';')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [31]:
print(dataset.head())

   country   age   salary purchased
0  prancis  44.0  72000.0       yes
1  spanyol  27.0  48000.0        no
2   jerman  30.0  54000.0       yes
3  spanyol  38.0  61000.0       yes
4   jerman  40.0      NaN        no


In [30]:
print(x)

[['prancis' 44.0 72000.0]
 ['spanyol' 27.0 48000.0]
 ['jerman' 30.0 54000.0]
 ['spanyol' 38.0 61000.0]
 ['jerman' 40.0 nan]
 ['prancis' 35.0 58000.0]
 ['spanyol' nan 61000.0]
 ['prancis' 48.0 79000.0]
 ['jerman' 50.0 83000.0]
 ['prancis' 37.0 67000.0]
 ['indonesia' 20.0 50000.0]
 ['prancis' 22.0 45000.0]
 ['indonesia' 45.0 21400.0]
 ['indonesia' 29.0 40000.0]]


In [32]:
print(y)

['yes' 'no' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'yes' 'no' 'yes' 'no' 'yes'
 'yes']


In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [34]:
print(x)

[['prancis' 44.0 72000.0]
 ['spanyol' 27.0 48000.0]
 ['jerman' 30.0 54000.0]
 ['spanyol' 38.0 61000.0]
 ['jerman' 40.0 56876.92307692308]
 ['prancis' 35.0 58000.0]
 ['spanyol' 35.76923076923077 61000.0]
 ['prancis' 48.0 79000.0]
 ['jerman' 50.0 83000.0]
 ['prancis' 37.0 67000.0]
 ['indonesia' 20.0 50000.0]
 ['prancis' 22.0 45000.0]
 ['indonesia' 45.0 21400.0]
 ['indonesia' 29.0 40000.0]]


In [35]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [36]:

print(x)

[[0.0 0.0 1.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 56876.92307692308]
 [0.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 61000.0]
 [0.0 0.0 1.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 20.0 50000.0]
 [0.0 0.0 1.0 0.0 22.0 45000.0]
 [1.0 0.0 0.0 0.0 45.0 21400.0]
 [1.0 0.0 0.0 0.0 29.0 40000.0]]


In [37]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [38]:
print(y)

[1 0 1 1 0 0 1 0 1 0 1 0 1 1]


In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [40]:
print(x_train)

[[0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 20.0 50000.0]
 [0.0 1.0 0.0 0.0 40.0 56876.92307692308]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 45.0 21400.0]
 [0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 29.0 40000.0]
 [0.0 0.0 1.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 0.0 22.0 45000.0]
 [0.0 0.0 1.0 0.0 35.0 58000.0]]


In [41]:

print(x_test)

[[0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 1.0 35.76923076923077 61000.0]]


In [42]:
print(y_train)

[1 1 0 0 1 1 1 0 1 0 0]


In [43]:
print(y_test)

[1 0 1]


In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [45]:
print(x_train)

[[0.0 1.0 0.0 -0.316227766016838 -0.4791502965599001
  -0.007341940391928278]
 [1.0 0.0 0.0 -0.316227766016838 -1.5547938194494721 -0.2603292840174229]
 [0.0 1.0 0.0 -0.316227766016838 0.5964932263296719 0.17461434136948523]
 [0.0 0.0 0.0 3.16227766016838 -0.8018433534267717 -0.3868229558301702]
 [1.0 0.0 0.0 -0.316227766016838 1.1343149877744578 -2.0691887909397093]
 [0.0 0.0 1.0 -0.316227766016838 1.0267506354855007 1.1311011059227976]
 [1.0 0.0 0.0 -0.316227766016838 -0.5867146488488574 -0.8927976430811594]
 [0.0 0.0 1.0 -0.316227766016838 0.2738001694628003 0.8148669263909292]
 [0.0 1.0 0.0 -0.316227766016838 1.6721367492192438 1.8268163008929077]
 [0.0 0.0 1.0 -0.316227766016838 -1.3396651148715577 -0.5765634635492911]
 [0.0 0.0 1.0 -0.316227766016838 0.058671464884885886 0.24564540323356632]]


In [46]:
print(x_test)

[[0.0 0.0 0.0 0.7071067811865476 -0.4869407000953254 -0.7071067811865476]
 [0.0 0.0 1.0 -1.414213562373095 1.3933253695796926 1.4142135623730951]
 [0.0 0.0 0.0 0.7071067811865476 -0.9063846694843684 -0.7071067811865476]]
